### PR TITLE
added italian translations 🇮🇹 #155

### LINKED ISSUE #155: Any plans for Italian to be supported?

### PR DESCRIPTION
**Pull request by alnitak**
fix #155

### CODE REVIEW

**Comment by Allan-Nava** [comment]
+1

**Comment by passsy** [comment]
Grazie per il rapido aiuto!

**Comment by Allan-Nava** [comment]
Good job! @alnitak

**Comment by alnitak** [comment]
You're welcome! It was my pleasure, though I didn't do anything special. Great project anyway!!

**Pull request merged**
