### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by huextrat**
**Added French translations**

By the way, if the translation is too long for the screenshot, we end up with an overflow (see screenshot).

I solved by reducing the length of the translations. But you would have to modify `capture.dart` & `_buildBottomMenu()` to have something flexible.

<details>
  <summary>Overflow capture</summary>

</details>

### CODE REVIEW

**Comment by orestesgaolin** [comment]
Thanks for reporting. WIll try to fix it asap

**Comment by orestesgaolin** [comment]
We really appreciate the translation! However, we would love you for the next time to contribute translations through POEditor project. I've just imported your translations and they are already visible on POEditor.

Few remarks:
- please fix analyzer issue with imports order in wiredash_localizations.dart
- if you wish please add your nickname in README.md in the translation contributors section

**Comment by huextrat** [comment]
Oh, yeah, I didn't see the link with POEditor, my mistake :)
I've corrected the warnings from the analyzer :)

**Comment by flschweiger** [comment]
Looks good to me, thanks for your contribution 👍

**Pull request merged**
