### PR TITLE
Remove Provider dependency

### PR DESCRIPTION
**Pull request by brianegan-wiredash**
Hey there! When I first started playing with this library, I immediately ran some dependency version conflicts. Therefore, I decided to take a look at the dependencies this package uses and try to cut down on them.

The first stop: Remove the `Provider` package. It's used in a couple of place and can be easily replaced by two InheritedWidgets + some AnimatedBuilders.

### CODE REVIEW

**Comment by passsy** [comment]
Great!

The downside of this is that new features have to build InheritedWidgets instead of using the elegant Provider API. This makes it (slightly) harder to play around with the sdk and add new features. It also adds a new point of possible bugs when someone forgets to update `updateShouldNotify`.

The upside, preventing dependency conflicts is real and overweights the maintenance overhead.

Anyways, I'm interested in the actual version conflicts you encountered. Could it be solvable by widening the dependency range?

**Comment by brianegan-wiredash** [comment]
> Anyways, I'm interested in the actual version conflicts you encountered. Could it be solvable by widening the dependency range?

I ran into the `file` issue that was resolved last week and it prompted me to look into the dependencies being used here in general :) Yes, provider is elegant, but I'd like to see if we can cut the number of them down overall.

I'd like to take a look at `shared_preferences` and `file` next, but those require a bit more thought!

**Comment by flschweiger** [comment]
I agree with @brianegan-wiredash here, I didn't add `Provider` in the first place because I wanted to keep external dependencies at a minimum. However, after some discussions I decided to introduce `Provider` (cause it's well tested and why invent the wheel for the 2nd time) but I start regretting it because of version conflicts which are also starting to appear with other dependencies.

I think it makes sense to put in this extra effort for building a rock-solid SDK so the devs have a flawless experience while using it.

**Comment by orestesgaolin** [comment]
I really like how provider was replaced with minimal changes to the code

**Comment by roughike** [comment]
I think this is a welcome change. I personally found it weird that there was a provider dependency in the first place ¯\\_(ツ)_/¯ 

> I'd like to take a look at shared_preferences and file next, but those require a bit more thought!

Feel free to get rid of `file`! I added the dependency in #72. Specifically, [this](https://github.com/wiredashio/wiredash-sdk/blob/1e290511a4b9335d037a3ceba97e5655042210dc/test/feedback/data/pending_feedback_item_storage_test.dart) and [this](https://github.com/wiredashio/wiredash-sdk/blob/1e290511a4b9335d037a3ceba97e5655042210dc/test/feedback/data/retrying_feedback_submitter_test.dart) are the tests that use `MemoryFileSystem.test()` from `file`.

The `file` package is only used in order to make testing easier in those two test files.

My lazy self didn't bother to create an abstraction for the file system, so I just used a package for it.

shame. on. me!

**Comment by brianegan-wiredash** [comment]
Merged as part of the Accessibility improvements.

**Pull request closed without merging**
