### PR TITLE
Remove FloatingEntryPoint

### PR DESCRIPTION
**Pull request by roughike**
Removes this thing:

image

from the Wiredash SDK.

## "But why?! I liked it!"
The reason for adding the floating button in the first place was to make it faster for new users to see Wiredash SDK in action.

Based on user feedback, it confused some users, myself included. We (at my workplace) updated Wiredash to the newest version and wondered what that button thingy was. By reading the code we could see that it's probably not shown in release mode. In debug mode it could be hidden by setting `showDebugFloatingEntryPoint: false`, but having to do that feels a bit unintuitive if most people end up disabling the button anyway (just a hunch).

I think that instead of having this button, it would be a better idea to have a copy-pasteable code sample that demonstrates launching Wiredash feedback flow and that can be run out of the box.

### CODE REVIEW

**Review by flschweiger — APPROVED** [review]
Goodbyes are not forever. Goodbyes are not the end. They simply mean I'll miss you until I see you again. Bye, bye `FloatingEntryPoint` 👋 

Feel free to let him go.

**Comment by flschweiger** [comment]
@roughike Seems like `FloatingEntryPoint` doesn't want to go that easily. Could you show him the door and resolve the conflicts? Thanks 😊

**Comment by roughike** [comment]
Conflicts resolved ✅

**Comment by orestesgaolin** [comment]
Farewell! You will stay in my memories for a long time.

**Pull request merged**
